databases:
  - name: location_tracker
    databaseName: location_tracker
    user: location_tracker

services:
  - type: web
    name: location_tracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn location_tracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: location_tracker
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4